---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/elizabethjpeakart
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp earlyworks.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp mail.php $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp resume.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp vue.js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
